### ISSUE TITLE
请问本仓库作者是薪典团队的吗？

### ISSUE THREAD

**Issue by laubonghaudoi** [xunux/hakka-culture#1]
薪典就是这个网站：http://syndict.com/

**Comment by xunux** [comment]
薪典站长算是认识，本人也有在薪典添加词条，但算不上薪典团队人员。我制作的词库来源多方面，有薪典的，还有台湾客语字典的，以及其他地方收集的和自己编写的。文件夹里都有说明

**Comment by laubonghaudoi** [comment]
我之前联系到了薪典的站长，其网站帐号在此
https://github.com/syndict
请问你能否和站长合作整理一下这个仓库里的资料，将Rime方案码表配方化？格式很简单，新建一个仓库并将Rime的两个.schema.yaml和.dict.yaml上传上去就行了，参考这个[南宁白话方案](https://github.com/leimaau/naamning_jyutping)
如果能将此方案配方化，就能在小狼毫和iRime上一键下载使用客家话拼音方案，非常方便。很感谢你们的贡献。

**Comment by xunux** [comment]
好的，等有时间我单独建个仓库弄下

**Comment by laubonghaudoi** [comment]
無需另外新建倉庫，只用直接和站長聯繫，在他[這個倉庫](https://github.com/syndict/hakka)裏更新維護即可。因為配方地址一旦確定就不能更改，新建太多倉庫容易造成混亂

**Comment by xunux** [comment]
嗯，我跟薪典站长联系过了。他也是这个意思，打算一起整理下，仓库地址用你提供的那个 [syndict hakka](https://github.com/syndict/hakka)

**Comment by xunux** [comment]
老哥你账号名有点意思，具体啥含义😄

**Comment by laubonghaudoi** [comment]
好的，非常感谢你们的贡献，期待能在全平台用到你们的客家话拼音方案。我的帐号名就是“刘邦后代”的粤拼而已，没什么深意。

**Comment by LukeBriton** [comment]
很遗憾 syndict/hakka 自19年的早期上传工作后再未更新，未能如隔壁rime-cantonese般建立起常态的维护、更新机制。

**Comment by LukeBriton** [comment]
即便稍新的fork https://github.com/Language-Preservation-Community/hakka 上次更新也已5年前。
